name: CI/CD Pipeline with Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Optional: List files to verify structure
      - name: List Project Files
        run: ls -la
        working-directory: ./To-Do

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: ./To-Do

      - name: Run Tests
        run: npm test
        working-directory: ./To-Do

      - name: Build Project
        run: npm run build
        working-directory: ./To-Do

      - name: Upload Build Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./To-Do/build

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js for Security Scan
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies for Scan
        run: npm install
        working-directory: ./To-Do

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
