name: CI/CD Pipeline with Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code from the repository root
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment (using Node.js 16)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install project dependencies (assumes package.json is at the repository root)
      - name: Install Dependencies
        run: |
          cd todo
          npm install

      # 4. Build the application (your build script in package.json should output to an appropriate folder)
      - name: Build Application
        run: |
          cd todo
          npm run build

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # 5. Check out the code again for the security scan context
      - name: Checkout Code
        uses: actions/checkout@v3

      # 6. Set up Node.js environment for Snyk
      - name: Setup Node.js for Security Scan
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 7. Install dependencies for the security scan (so Snyk can analyze your project)
      - name: Install Dependencies for Security Scan
        run: |
          cd todo
          npm install

      # 8. Run Snyk vulnerability scan on your project dependencies
      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
